### ISSUE TITLE
Default Colab Demo installation issues

### ISSUE THREAD

**Issue by KT9000** [Arthur151/ROMP#100]
I was just testing the Colab Demo without any changes on a V100 / CUDA 11.2 / Python 3.7.12 and ran into following errors.

When installing the CUDA libs and libc:
`/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link`

Later at romp.predict.image:
`ImportError: /usr/local/lib/python3.7/dist-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor2leERKN3c106ScalarE`

**Comment by Arthur151** [comment]
This is the caused by installation failure of pytorch3d. 
Note that for now installing pytorch3d via pip only supports Pytorch1.9 and CUDA 10.2, see [here](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#3-install-wheels-for-linux).
Sadly, Pytorch1.9 is not currently available now..
I will add the support for rendering results via Pyrender later. For now, the situation is prettey ackward...

**Comment by VimalMollyn** [comment]
You can install pytorch 1.9.0 through conda:

```conda install -n test pytorch==1.9.0 torchvision torchaudio cudatoolkit=10.2 -c pytorch```. I'm testing out if this resolves the issue!

- Vimal

**Comment by VimalMollyn** [comment]
> You can install pytorch 1.9.0 through conda:
> 
> `conda install -n env_name pytorch==1.9.0 torchvision torchaudio cudatoolkit=10.2 -c pytorch`. I'm testing out if this resolves the issue!
> 
> Vimal

This seems to resolve the issue! I've submitted a pull request with some other changes that I had to make in order to get the video demo to work. Thanks for the awesome repo and congrats on the paper!

Vimal

**Comment by Arthur151** [comment]
Thanks, Vimal,
This is really helpful. 
Best,
Yu
