### ISSUE TITLE
Training data ‘cv2.error’ in resize some images

### ISSUE THREAD

**Issue by littlejiumi** [Arthur151/ROMP#123]
The data of the 7 datasets are randomly selected for training, right? The training code can run successfully for a period of time (not more than one epoch), and then will encounter this error. Can you tell the reason? I don't know much about it，TTTThank you!

```
File "/root/Downloads/ROMP_ALL/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 231, in prepare_image

    dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)

cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-24v3eisa/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'Mat'
```

**Comment by littlejiumi** [comment]
OR can you tell me your version of OPENCV?

**Comment by Arthur151** [comment]
Sorry for the unpleasant bugs. 
My Opencv is 4.1.1 on a remote server. But the version may not matter. 

According to the issues submited by other users, this bug is caused by that some image is empty / failed to read via cv2. You can avoid this via try, except, for instance 
'''
try:
    dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)
except:
    dst_image = np.zeros((self.input_shape[0], self.input_shape[1], 3))
'''

Welcome to discuss if there is any problem related to ROMP that bother you.
