### ISSUE TITLE
perspective_projection

### ISSUE THREAD

**Issue by HuiliCui** [Arthur151/ROMP#241]
hello，I have a question about projection. I want to use verts and cam_trans for projection results. Here's how I did it
![image](https://user-images.githubusercontent.com/62087070/168859124-1c101c50-cb12-454f-a885-ee8772bac016.png)
But the result is wrong. What can I do to get the right result?

**Comment by Arthur151** [comment]
Hi, Huili Cui,
This is a good one.

The problem is that we estimate the camera parameters for people in input image (padded to square), instead of original image. 
So if you use the padded input image (just to pad the shorter edge to make it square), I think it would be fine.
Then you can substract the padded length to convert the pro_vert to original image. 

It would be very helpful to debug if you can provide visual results.
