### ISSUE TITLE
Question about details for the BEV model training

### ISSUE THREAD

**Issue by JosephKKim** [Arthur151/ROMP#361]
Hi thanks for the wonderful work!
I am trying to replicate this nice work, in my environment. Before diving in to reproduction I have a few questions. 

1. From the supplement material I know that BEV is trained with 4 V100 GPUs which is know to have 24 GB memory.
Since I can only utilize 3090 GPUs, that matches the required memory, I will have to use CUDA version 11.x. 
Your installation.md make me to install cuda 10.2.. so will it work in 3090 GPUs (with just small modification maybe)?

2. How long will it takes to train from scratch using 3090? or with V100 how long did it take?

Thanks! :)

**Comment by Arthur151** [comment]
Yes, It would work. 
I also train BEV on a 3090Ti (24GB like 3090) with latest CUDA. The CUDA version is flexible supported if you can compile the Pytorch3D from source. 
From scratch, it may takes over 2 weeks. The performance is relied on a pretraining stage on 2D pose estimation. I really recommand to start from the pretrained weight of HRNet-32 for 2D pose estimation, which you can obtain from 
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation
Otherwise, it would be very hard to train well from simple initialization of weights only. 
Welcome to more discussion.
Best,
Yu

**Comment by JosephKKim** [comment]
Thanks for the detailed reply!
I was trying to extend research starting from your nice work ROMP and got worried about training process because both ROMP and BEV seems like a large model to be trained + dependencies in CUDA and other different environments.


So what you said is that if I start from HRNet pretrained weights will it converge in less than 2weeks? Cause I can only utilized limited GPU resources I want to conduct as many experiments as possible.

Thanks again for the detailed reply!
Best, 
Joseph.

**Comment by Arthur151** [comment]
Yes, good pretraining has obvious influence in both training time and final performance. 
Of course, you can also directly use the backbone weights of ROMP for fine-tuning.
