### ISSUE TITLE
can't use GPU resourece in training

### ISSUE THREAD

**Issue by Hellominsusu** [Arthur151/ROMP#428]
Thank you for sharing your project. As a college student, there was a problem while trying to use the training code you provided. I turned the training code on both Google colab and the local environment, but the learning process is not progressing because the GPU is not used in the learning process. I'd like to a
![error](https://user-images.githubusercontent.com/93136421/224678118-ab56a616-a200-4dff-8ffc-b7898393b60b.jpg)
sk you for a solution in this regard.

code according to git read me file

**Comment by Arthur151** [comment]
As the log showing, the reason is that it can't find the image to load for training. 
You need to properly set the path of each dataset to enable training. 
For instance, please properly set the path to the folder of Relative Human at
https://github.com/Arthur151/ROMP/blob/12a624f00be92d1f7195f24106d151d2f26961f4/romp/lib/dataset/relative_human.py#L20

Please let me know if the same errors keep showing.

**Comment by Hellominsusu** [comment]
Thank you for your answer. however still my dataset root set that follow your git .md, 
my critical problem is when training dataset, all dataset trained by cpu not gpu. if you can watch my screen image, when train dataset computer only uses cpu memory. ans does not use gpu memory and resource. i don't understand how can use gpu memory & resource.
