### ISSUE TITLE
URL error!

### ISSUE THREAD

**Issue by xangs** [Arthur151/ROMP#450]
Not valid url in main.py: https://github.com/Arthur151/ROMP/releases/download/V2.0/smpl_packed_info.pth

**Comment by Arthur151** [comment]
Hi, @xangs ,

Thanks for your bug report!!
Due to the license problem, we no longer provide SMPL file. 
Instead, please follow the instrcution 
https://github.com/Arthur151/ROMP/tree/master/simple_romp#installation
 to prepare the SMPL model file, including smpl_packed_info.pth

For now, you will have to run 
```
cd simple_romp
sh reinstall.sh
```
to get the latest simple-romp. I will update the pip resource later.

**Comment by xangs** [comment]
Thanks

**Comment by Arthur151** [comment]
Please refer to https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md
Now we have:
```
pip install simple-romp==1.1.1
```
