### ISSUE TITLE
TRACE needs SMPL_NEUTRAL.pth 

### ISSUE THREAD

**Issue by gauku-sr** [Arthur151/ROMP#454]
See: line 10-11 in `simple_romp/trace2/utils/visualize_results.py`, where can I find this .pth file that is loaded in torch later on

**Comment by botaoye** [comment]
same problem

**Comment by Arthur151** [comment]
@botaoye  and @gauku-sr 
Thanks for reporting this!!
Due to the license problem, now we may need to convert the original SMPL model files (SMPL_NEUTRAL.pkl) to (SMPL_NEUTRAL.pth) as following
https://github.com/Arthur151/ROMP/blob/master/simple_romp/trace2/README.md 
The converted model (SMPL_NEUTRAL.pth) would be put to `~/.romp/` in defualt.

Let me konw if there are anything wrong.

Best,
Yu

**Comment by gauku-sr** [comment]
Thanks for a quick reply and also for making your code available. 

Yes, I was able to find the .pth image in the ~/.romp folder where the conversion script put it. Thanks again.
