### ISSUE TITLE
romp.pack_smpl_info：no commond found

### ISSUE THREAD

**Issue by neverstoplearn** [Arthur151/ROMP#474]
romp.pack_smpl_info -source_dir=/home/zhengxin/ROMP/smpl_model_data --gender='female' romp.pack_smpl_info：no commond found
I try simple-romp 1.1.1 and simple-romp 1.1.3,got the same error.how can i fix it?

**Comment by Arthur151** [comment]
@neverstoplearn 
I guess you should have installed many verison of simple-romp. 
You should first repeatly run 
```
pip uninstall simple-romp
```
until nothing shows up. 

Then you can install the latest simple-romp and everything should be fine.

**Comment by alvaro-budria** [comment]
I tried this approach but it didn't work. I tried installing both with `pip install simple_romp==1.1.3` and with `python setup.py install`.

I don't know anything about this library. Is it a missing path maybe?

**Comment by ahmadkhajehnejad** [comment]
I guess I found the solution. In fact, I think the documentation is wrong, and we should run "romp.prepare_smpl" instead of "romp.pack_smpl_info". So the correct commands will be:

romp.prepare_smpl -source_dir=/path/to/smpl_model_data --gender='female'
romp.prepare_smpl -source_dir=/path/to/smpl_model_data --gender='male'

We also need to copy files SMPL_MALE.pkl and SMPL_FEMALE.pkl from SMPL_python_v.1.1.0 (where we found the file SMPL_NEUTRAL.pkl) into smpl_model_data directory, before running the above commands.

I did this way and the files SMPL_FEMALE.pth, SMPLA_FEMALE.pth, SMPL_MALE.pth, and SMPLA_MALE.pth were generated in ~/.romp directory. I hope it is the correct way.

**Comment by SFGHRT** [comment]
> 我想找到解决方案。事实上，我认为文档是错误的，我们应该运行“romp.prepare_smpl”而不是“romp.pack_smpl_info”。因此正确的命令将是：
> 
> romp.prepare_smpl -source_dir=/path/to/smpl_model_data --gender='female' romp.prepare_smpl -source_dir =/path/to/smpl_model_data --gender='male'
> 
> 在运行上述命令之前，我们还需要将文件 SMPL_MALE.pkl 和 SMPL_FEMALE.pkl 从 SMPL_python_v.1.1.0（我们在其中找到了文件 SMPL_NEUTRAL.pkl）复制到 smpl_model_data 目录中。
> 
> 我按照这种方式操作，在 ~/.romp 目录中生成了 SMPL_FEMALE.pth、SMPLA_FEMALE.pth、SMPL_MALE.pth 和 SMPLA_MALE.pth 文件。我希望这是正确的方法。
romp.prepare_smpl -source_dir=/workspace/psen/ROMP-master/smpl_model_data
kintree_table
J_regressor_extra9
J_regressor_h36m17
shapedirs
posedirs
extra_joints_index
f
v_template
J_regressor
weights
kintree_table
J_regressor_extra9
J_regressor_h36m17
shapedirs
posedirs
extra_joints_index
f
v_template
J_regressor
weights
smpla_shapedirs
Why does this happen when I convert files? Where can I download these files?
