### ISSUE TITLE
Cannot find romp.pack_smpl_info

### ISSUE THREAD

**Issue by alvaro-budria** [Arthur151/ROMP#482]
When I run `romp.pack_smpl_info -source_dir=dir --gender='female'` I get the following error:

`romp.pack_smpl_info: command not found`

There is a previous issue #474 about this same problem. However, the solution given there did not work out for me...
I tried installing `simple-romp`  both with `pip install simple_romp==1.1.3` and with `python setup.py install`.

Any help is appreciated.

**Comment by ahmadkhajehnejad** [comment]
I have the same problem :(  Any updates?

**Comment by ahmadkhajehnejad** [comment]
I guess I found the solution. In fact, I think the documentation is wrong, and we should run "romp.prepare_smpl" instead of "romp.pack_smpl_info". So the correct commands will be:

romp.prepare_smpl -source_dir=/path/to/smpl_model_data --gender='female'
romp.prepare_smpl -source_dir=/path/to/smpl_model_data --gender='male'

We also need to copy files SMPL_MALE.pkl and SMPL_FEMALE.pkl from SMPL_python_v.1.1.0 (where we found the file SMPL_NEUTRAL.pkl) into smpl_model_data directory, before running the above commands.

I did this way and the files SMPL_FEMALE.pth, SMPLA_FEMALE.pth, SMPL_MALE.pth, and SMPLA_MALE.pth were generated in ~/.romp directory. I hope it is the correct way.
