### ISSUE TITLE
low FPS 

### ISSUE THREAD

**Issue by bhumikasinghrk** [Arthur151/ROMP#52]
hey @Arthur151, great framework.
but I have one issue, i tried executing it in the google colab environment on a video of 446 frames, took 153 seconds.
The fps is < 3fps, also tried on AWS got almost same around 3.5 fps there.
Is there something i am missing or that's all we can get ?

**Comment by Arthur151** [comment]
No, the main reason is the visualizaiton part (for rendering mesh on the image).
If you can try our [Web cam demo](https://github.com/Arthur151/ROMP#webcam), the FPS would be 20~30 depending on the checkout you use and your GPU device. 
Here is the [docs](https://github.com/Arthur151/ROMP/blob/master/docs/evaluation.md#test-fps) about how to evaluate the FPS

**Comment by bhumikasinghrk** [comment]
Thanks for your quick response and guidance @Arthur151. I tried with commenting out the visualization part the FPS went up to 12 fps.I am working on AWS instance running on Tesla T4 with 16Gb ram. Can you tell me which GPU instance you use to get around 20-30 fps?

**Comment by Arthur151** [comment]
As we stated in the [docs](https://github.com/Arthur151/ROMP/blob/master/docs/evaluation.md#test-fps), the runtime is evaluated on a desktop with a 1070Ti GPU, Intel i7-8700K CPU, and 8 GB RAM.
As the speed rand presented in the [leaderboard](https://technical.city/zh/video/rating#result3640) (where Tesla T4 ranks 98 while 1070Ti ranks 60), it could be caused by the GPU device.
Besides, if your try to use our ResNet-based model, it could be faster.

**Comment by bhumikasinghrk** [comment]
switched the backbone to resnet50, improved the FPS to 14 .
Also, i have 1080Ti GPU but the underlying OS is Windows. Can i run this with windows, or will i encounter compatibility issues?

**Comment by Arthur151** [comment]
I haven't tried to install ROMP on Windows. ROMP only use some common libraries. Maybe we can try to make it work togather.

**Comment by Gowan1998** [comment]
@Arthur151 Hello,
I have tried the single_image and webcame approach. In both cases I get very low fbs.
I also tried the tests on two different systems. One with a GTX 1050 and one with a RTX2080 Ti.
I made sure to turn off visualization in both tests so rendering is not the problem. 

               | single_image [fps]  |   webcame  [fps]
-------------------------------------------------------------------------
1050       |       10                     |         6
2080 TI   |       20                     |         8

Especially the tests with the webcam were very slow. Even when I commented out any kind of visualization in the test.py

**Comment by Arthur151** [comment]
I am not sure about the fps on 1050. But it is supposed to be much faster on 2080Ti. The low fps on webcam is really wierd. 
Without the visualizaiton part, the speed is just the forword past of the resnet model. 
Let's try to turn off the webcam_mesh_color, so you can use the open3d visualizer instead of vedo.
Could you please post your config setting here? So I can locate the problem.

**Comment by Gowan1998** [comment]
Hello Arthur, 
I have used male_tex once and ghostwhite once. Using ghostwhite is faster. I also tried to commet out all kind of the visualization and process only the images coming from the camera. But I am still at 10 fps.

Here my config:
![Screenshot from 2021-08-13 18-10-52](https://user-images.githubusercontent.com/22528147/129388438-758ba499-29f5-4269-bb28-0ad6f5c22a06.png)

**Comment by Arthur151** [comment]
Sorry for the delayed reply. Have you tested the speed of simply running the feedforward of ResNet-50? If you drop the visualization part. Then the speed is mostly limited by this.
We are working on this. 
In the brand new version of ROMP that we are developing these days, the old visualization system might get totally replaced. 
We are developing the multi-person visualization system. While the speed of rendering is not satisfying. Therefore, we are looking for the alternative plan. In the new version, we used the latest Pytorch 1.9.0.  Welcome to try it later.

**Comment by Gowan1998** [comment]
Hello,
yes I have done that. The values you can see in my comment 10 days ago were collected just like that. I commented out all libs and commands that use any kind of visualization.

I had some concerns about something being unstable or torch being too outdated (because of cuda and some other related things). So great that you updated the torch lib.When will the new changes be published?

**Comment by Arthur151** [comment]
Hi, I think I have finally located the bug that results in the low FPS.
It's because the repeated args paring process in config.py. 
If you want to achieve over 24+ FPS (HRNet-32). You just need to replace the original args() function in lib/config.py with this new one:
```
def args():
    return ConfigContext.parsed_args
```
Please tell me if there are any problem.
