### ISSUE TITLE
Conversion of Onnx Model

### ISSUE THREAD

**Issue by Secondgrade** [Arthur151/ROMP#94]
Hi,
I am following this work and really appreciate your efforts on this project. I just want to know if there is a plan of build a pipe for converting the whole ROMP model into a onnx model. And if there is not, do you mind distribute some clues so this job could be completed by followers of thie repository.

**Comment by Arthur151** [comment]
Hi, Secondgrade,
Thanks for your attension. WE really appreciate that. 
I have tried to convert the ROMP mode into ONNX. But the progress got stuck. Because some layers of HRNet-32 wasn't supported well by the converter tool. I don't know the current status of this field. 
It would be great that the great Github developers can contribute to this.
Thanks!
Best regards,
Yu
